---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: username/order:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deliver
  labels:
    app: Deliver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Deliver
  template:
    metadata:
      labels:
        app: Deliver
    spec:
      containers:
        - name: Deliver
          image: username/Deliver:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext585
  labels:
    app: BoundedContext585
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext585
  template:
    metadata:
      labels:
        app: BoundedContext585
    spec:
      containers:
        - name: BoundedContext585
          image: username/BoundedContext585:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order


---


apiVersion: v1
kind: Service
metadata:
  name: Deliver
  labels:
    app: Deliver
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Deliver


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext585
  labels:
    app: BoundedContext585
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext585

